#!/bin/bash

echo ":) Start simulation iot-project-dizzy-home"

val=$(lsusb | grep -c Arduino)

if [ $val -eq 3 ]; then
echo "Right number of Arduino connected"

echo "Start the ML_sub script"
python -W ignore ML_sub.py > /dev/null &
echo "Start the read_and_publish script"
./read_and_publish.py > /dev/null &
# echo "Start the Mqtt local-cloud bridge"
# ./mqtt_local_cloud_bridge/mqtt_local_cloud_bridge > /dev/null &
# echo "Start the serial communicaton script"
# ./raspy_serial_full_duplex_arduino/serial_read_write_mqtt_clients.py
else
echo "Not all Arduino connected"
fi


